#!/bin/bash
# Made by Jishnu Joy
# cmd creadit hopingboyz

# download
git clone https://github.com/JishnuTheGamer/Ptero-codsanbox.git && cd Ptero-codsanbox && apt install zip -y && unzip ptero-codesanbox.zip && bash ptero-codesanbox.txt
